name: Terraform checks
on: [push, pull_request]

jobs:
  terraform-linter:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init-bastion
        run: |
          cd modules/terraform-zspse-bastion-gcp
          terraform init   

      - name: Terraform Validate
        id: validate-bastion
        run: |
          cd modules/terraform-zspse-bastion-gcp
          terraform validate -no-color

      - name: Terraform Init
        id: init-zspse-acvm
        run: |
          cd modules/terraform-zspse-vm-gcp
          terraform init   

      - name: Terraform Validate
        id: validate-zspse-acvm
        run: |
          cd modules/terraform-zspse-vm-gcp
          terraform validate -no-color

      - name: Terraform Init
        id: init-zspse-network-gcp
        run: |
          cd modules/terraform-zspse-network-gcp
          terraform init   

      - name: Terraform Validate
        id: validate-zpa-zspse-network-gcp
        run: |
          cd modules/terraform-zspse-network-gcp
          terraform validate -no-color
  
      - name: Terraform Init
        id: init-zpa-service-edge-group
        run: |
          cd modules/terraform-zpa-service-edge-group
          terraform init   

      - name: Terraform Validate
        id: validate-zpa-service-edge-group
        run: |
          cd modules/terraform-zpa-service-edge-group
          terraform validate -no-color
  
      - name: Terraform Init
        id: init-zpa-provisioning-key
        run: |
          cd modules/terraform-zpa-provisioning-key
          terraform init   

      - name: Terraform Validate
        id: validate-zpa-provisioning-key
        run: |
          cd modules/terraform-zpa-provisioning-key
          terraform validate -no-color
